specVersion: "1.0.0"

name: "uniswap-v3"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your new Ethereum SubQuery project"
repository: "https://github.com/subquery/ethereum-subql-starter"

schema:
  file: "./schema.graphql"

network:
  endpoint: "https://eth.api.onfinality.io/public"
  chainId: "1"
  dictionary: "https://eth-dict.api.onfinality.io/"

dataSources:
  - kind: ethereum/Runtime
    startBlock: 12369621
    options:
      # Must be a key of assets
      abi: Factory
      address: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
    assets:
      Factory:
        file: "./abis/Factory.json"
      ERC20:
        file: "./abis/ERC20.json"
      ERC20SymbolBytes:
        file: "./abis/ERC20SymbolBytes.json"
      ERC20NameBytes:
        file: "./abis/ERC20NameBytes.json"
      Pool:
        file: "./abis/pool.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handlePoolCreated
          kind: ethereum/LogHandler
          filter:
            address: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
            topics:
              - PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
templates:
  - name: Pool
    kind: ethereum/Runtime
    assets:
      Pool:
        file: "./abis/pool.json"
      Factory:
        file: "./abis/factory.json"
      ERC20:
        file: "./abis/ERC20.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleInitialize
          kind: ethereum/LogHandler
          filter:
            topics:
              - Initialize (uint160 sqrtPriceX96, int24 tick)